#!/bin/bash
if [ "$(pidof i3)" != "" ]; then
	IN=/tmp/lockinpipe.png
	OUT=/tmp/lockoutpipe.png
	mkfifo $IN
	mkfifo $OUT
	scrot $IN &
	convert $IN -scale 10% -scale 1000% $OUT&
	i3lock -e -i $OUT
	rm $IN
	rm $OUT
fi
